/*
 * generated by Xtext 2.21.0
 */
package com.gui.compiladores.alguma;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlgumaRuntimeModule extends AbstractAlgumaRuntimeModule {
}
