/*
 * generated by Xtext 2.21.0
 */
package com.gui.compiladores.alguma;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AlgumaStandaloneSetup extends AlgumaStandaloneSetupGenerated {

	public static void doSetup() {
		new AlgumaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
